steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/thedoers:${SHORT_SHA}",
        "-t",
        "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/thedoers:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/thedoers:latest"]
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
    - run
    - --filename=kubernetes.yaml
    - --image=${_REGISTRY_URL}/$PROJECT_ID/${_REGISTRY}/thedoers:latest
    - --location=us-central1
    - --cluster=${_CLUSTER_NAME}

