apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "thedoers-canary"
  namespace: "default"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "thedoers"
      release: "latest"
  template:
    metadata:
      labels:
        app: "thedoers"
        release: "latest"
    spec:
      containers:
      - name: "thedoers"
        image: "us-central1-docker.pkg.dev/k8-playground-artiq/todos/thedoers:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: artifact-registry

---
apiVersion: v1
kind: Service
metadata:
  name: thedoers
spec:
  selector:
    app: thedoers
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer

