apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "helloworld"
  namespace: "default"
  labels:
    app: "helloworld"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "helloworld"
  template:
    metadata:
      labels:
        app: "helloworld"
    spec:
      containers:
      - name: "helloworld"
        image: "us-central1-docker.pkg.dev/k8-playground-artiq/todos/helloworld:latest"
        imagePullPolicy: Always
      imagePullSecrets:
        - name: artifact-registry